# Generated by Django 6.1.1 on 2026-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('did_you_know', 'Did You Know?'), ('breakthrough', 'Engineering Breakthrough'), ('inventor', 'Inventor Spotlight'), ('principle', 'Engineering Principle'), ('milestone', 'Historical Milestone'), ('innovation', 'Modern Innovation'), ('africa', 'African Engineering'), ('kenya', 'Kenyan Engineering'), ('energy', 'Energy & Sustainability'), ('technology', 'Technology')], default='did_you_know', max_length=30)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
