# Generated by Django 6.1.1 on 2026-09-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CAT', 'CAT'), ('Main', 'Main')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online'), ('Take-away', 'Take-away')], max_length=10)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('online_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
