# Generated by Django 6.1.1 on 2026-09-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
