# Generated by Django 6.1.1 on 2026-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='unit_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
