# Generated by Django 6.1.1 on 2026-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_timetableentry_unit_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetableentry',
            old_name='lecture',
            new_name='lecturer',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='mode',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=10),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='online_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
