# Generated by Django 6.1.1 on 2026-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_rename_lecture_timetableentry_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
    ]
