# Generated by Django 6.1.1 on 2026-09-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('past_paper', 'Past Examination Paper'), ('past_cat', 'Past CAT Test'), ('solution', 'Solutions and Marking Schemes'), ('lab_material', 'Laboratory Materials'), ('reference', 'Reference Materials'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='units.unit')),
            ],
        ),
    ]
