# Generated by Django 6.1.1 on 2026-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyResources',
            new_name='StudyResource',
        ),
    ]
