# Generated by Django 6.1.1 on 2026-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_studyresources_studyresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
