# Generated by Django 6.1.1 on 2026-10-02 17:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_studyresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyresource',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
